production:
  sales_summary_report:
    class: SalesSummaryReport
    queue: background
    args: []
    schedule: every hour
  subscriptions_summary_report:
    class: SubscriptionsSummaryDailyJob
    queue: background
    args: []
    schedule: every hour
