sales_summary_daily:
  class: SalesSummaryDailyJob
  queue: background
  args: []
  schedule: every hour
subscriptions_summary:
  class: SubscriptionsSummaryDailyJob
  queue: background
  args: []
  schedule: every hour
customer_reviews_daily:
  class: CustomerReviewsDailyJob
  queue: background
  args: []
  schedule: every hour
